# Generated by Django 4.0.6 on 2022-07-24 11:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_delete_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_main', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
    ]
