# Generated by Django 4.0.6 on 2022-07-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='listing',
            new_name='listing_id',
        ),
    ]
