# Generated by Django 4.0.6 on 2022-07-24 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_delete_attachment'),
        ('attachments', '0002_rename_listing_attachment_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='listing_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='listings.listing'),
        ),
    ]
