# Generated by Django 4.0.6 on 2022-07-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_alter_attachment_listing_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='listing_id',
            new_name='listing',
        ),
    ]
