# Generated by Django 4.0.6 on 2022-08-05 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0003_delete_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=256)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='listings.listing')),
                ('realtor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
