# Generated by Django 4.0.6 on 2022-07-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_attachment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
